### PR TITLE
docs(cn): translate src/content/loaders/json5-loader.md

### PR DESCRIPTION
**Pull request by jacob-lcs**
_describe your changes..._

docs(cn): 翻译 src/content/loaders/json5-loader.md

- [x] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [x] Make sure your PR complies with the [writer's guide][2].
- [x] Review the diff carefully as sometimes this can reveal issues.
- [x] Do not abandon your Pull Request: [Stale Pull Requests][3].
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

### CODE REVIEW

**Comment by chenxsan** [comment]
这个 [json5-loader](https://github.com/webpack-contrib/json5-loader) 在 webpack 5 下看起来已经弃用。因为文档是针对 webpack 5 的，所以似乎没有必要翻译？稍后我会从上游仓库里去掉它。

**Comment by jacob-lcs** [comment]
> 这个 [json5-loader](https://github.com/webpack-contrib/json5-loader) 在 webpack 5 下看起来已经弃用。因为文档是针对 webpack 5 的，所以似乎没有必要翻译？稍后我会从上游仓库里去掉它。

好的

**Comment by chenxsan** [comment]
上游仓库里去掉了 https://github.com/webpack/webpack.js.org/pull/4576

**Comment by jacob-lcs** [comment]
json5-loader 已废弃，本 PR 关闭

**Pull request closed without merging**
