### PR TITLE
226行，少写了一句const CleanWebpackPlugin = require('clean-webpack-plugin');

### PR DESCRIPTION
**Pull request by Jet12138**
参见 【指南》管理输出】 那章

_describe your changes..._

- [ ] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [ ] Make sure your PR complies with the [writer's guide][2].
- [ ] Review the diff carefully as sometimes this can reveal issues.
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/writers-guide/

### CODE REVIEW

**Comment by dear-lizhihua** [comment]
@Aladdin-ADD 这种不一定是缺了内容，可能是没合并 master 更新导致，合进去容易引起冲突

**Comment by Aladdin-ADD** [comment]
原文没有吗？下面代码有引用到，这个是算bug，还是觉的应该merge，要不然你向webpack-docs提个PR？ 😄

**Comment by dear-lizhihua** [comment]
其实想知道有没有很简单，把 cn 和 master 对比下。
如果行数上没差别，下次再合并 master 到 cn 必然会得到
如果行数上有差别，说明是上次合并 master 到 cn 遗漏造成的错误

**Comment by dear-lizhihua** [comment]
当然如果是官方代码本身错了也是有可能的，如果是这种情况，应该向上游的官方提交 issue 或 pr

**Pull request merged**
