### PR TITLE
docs(cn): translate src/content/configuration/configuration-types.md

### PR DESCRIPTION
**Pull request by doflamin**
…ation-types.md>

_describe your changes..._

- [ ] Read and sign the [CLA][1]. PRs that haven't signed it won't be accepted.
- [ ] Make sure your PR complies with the [writer's guide][2].
- [ ] Review the diff carefully as sometimes this can reveal issues.
- [ ] Do not abandon your Pull Request: [Stale Pull Requests][3].
- __Remove these instructions from your PR as they are for your eyes only.__

[1]: https://cla.js.foundation/webpack/webpack.js.org
[2]: https://webpack.js.org/contribute/writers-guide/
[3]: https://webpack.js.org/contribute/#pull-requests

### CODE REVIEW

**Comment by doflamin** [comment]
@yuqingc

**Comment by QC-L** [comment]
请注意排版问题，查看任务领取的顶部，有个排版指南，请修改一下 @doflamin

**Review by QC-L — CHANGES_REQUESTED** [review]
请尽快修改

**Comment by lcxfs1991** [comment]
@doflamin  请尽快修改哈

**Pull request closed without merging**
